openapi: 3.0.0
info:
  title: Video Processing API
  version: 1.0.0
  description: API for video processing operations including upload, trim, merge, and share

servers:
  - url: http://localhost:3000/api
    description: Development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

security:
  - BearerAuth: []

paths:
  /videos/upload:
    post:
      summary: Upload a video file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
      responses:
        '201':
          description: Video uploaded successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /videos/trim:
    post:
      summary: Trim a video
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                videoId:
                  type: integer
                startTime:
                  type: number
                endTime:
                  type: number
      responses:
        '200':
          description: Video trimmed successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /videos/merge:
    post:
      summary: Merge multiple videos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                videoIds:
                  type: array
                  items:
                    type: integer
      responses:
        '200':
          description: Videos merged successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /videos/share:
    post:
      summary: Create a share link for a video
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                videoId:
                  type: integer
                expiryHours:
                  type: integer
      responses:
        '200':
          description: Share link created successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /videos/shared/{token}:
    get:
      summary: Get a shared video by token
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: The share token for the video
      responses:
        '200':
          description: Video retrieved successfully
        '400':
          description: Invalid token
        '404':
          description: Video not found or share link expired